[theme]
primaryColor = "#f63366"
# backgroundColor = "#10344b"
backgroundColor = "#111111"
# secondaryBackgroundColor = "#154360"
secondaryBackgroundColor = "#393939"
textColor = "#C4C4C4"
font = "sans serif"

[ui]
hideTopBar = true
